### ISSUE TITLE
MemoManager코드 2/3업로드 완료

### ISSUE THREAD

**Issue by whoo1234** [whoo1234/HW2#12]
하지만 여전히 삭제 기능은 여러분들의 도움을 필요로하고 있습니다...
불쌍한 지후를 도와주세요...

**Comment by suminleeme** [comment]
ㅋㅋㅋㅋㅋㅋ 네 다른 과목 과제 내고 바로 코드 열어볼게요! 정말 열심히 일하는군요!  ^^
