### ISSUE TITLE
CalculatorBranchEdit1 브랜치에 패키지 se추가, CalculatorTest 이름변경, test 파일 추가했습니다.

### ISSUE THREAD

**Issue by suminleeme** [whoo1234/HW2#14]
CalculatorBranchEdit1 브랜치에 패키지 se추가,
 CalculatorTest 이름 변경(-> CalculatorProgram),
 test 파일(testCalculaotr) 추가했습니다. 나중에 브랜치 다 올라오면 merge하겠습니다.

**Comment by whoo1234** [comment]
package se는 마지막에 올릴 때 다 default로 수정했습니다!
